import { expect, test } from '@playwright/test'

test('moves through the representative FinMate mobile flow', async ({ page }) => {
  await page.goto('/signup')
  await page.getByLabel('이름').fill('민지')
  await page.getByLabel('이메일').fill('minji@example.com')
  await page.getByLabel('비밀번호').fill('finmate12345')
  await page.getByRole('button', { name: '시작하기' }).click()

  for (let step = 0; step < 5; step += 1) {
    await page.getByRole('button', { name: '다음' }).click()
  }
  await page.getByRole('button', { name: '여행 목표 보기' }).click()
  await page.getByRole('button', { name: '유럽 여행 자금 목표 만들기' }).click()
  await expect(page.getByRole('heading', { name: '여행까지 한 걸음' })).toBeVisible()
  await page.getByRole('button', { name: '홈으로 가기' }).click()
  await expect(page.getByRole('heading', { name: '유럽 여행 목표를 향해 가고 있어요.' })).toBeVisible()
  await page.getByRole('button', { name: '동물 리포트', exact: true }).click()
  await expect(page.getByRole('heading', { name: '오늘의 동물 리포트' })).toBeVisible()
  await page.getByRole('button', { name: '메이트 루틴 살펴보기' }).click()
  await page.getByRole('link', { name: /꾸준저축 원정대/ }).click()
  await page.getByRole('link', { name: /북쪽의 모험가/ }).click()
  await expect(page.getByRole('heading', { name: '주 3회 저축 챌린지' })).toBeVisible()
  await page.getByRole('link', { name: '루틴을 내 생활에 맞추기' }).click()
  await page.getByRole('button', { name: 'STANDARD 후보 선택' }).click()
  await page.getByRole('button', { name: 'STANDARD · 주 3회 저축 챌린지' }).click()
  await page.getByRole('button', { name: '이 루틴으로 바꾸기' }).click()
  await expect(page.getByRole('dialog', { name: '루틴 변경 확인' })).toBeVisible()
  await page.getByRole('button', { name: '교체 확정' }).click()
  await expect(page.getByRole('heading', { name: '활성 루틴이 바뀌었어요' })).toBeVisible()
  await page.getByRole('link', { name: '홈' }).click()
  await expect(page.getByText('현재 루틴: 월요일 저축 확인')).toBeVisible()
  await expect(page.getByText('유럽 여행', { exact: true })).toBeVisible()
  await expect(page.getByText('2,000,000 KRW')).toBeVisible()
  await page.getByRole('link', { name: '퀘스트' }).click()
  await page.getByRole('button', { name: '자동저축 입금 반영 확인하기 완료' }).click()
  await expect(page.getByRole('status')).toContainText('XP 5')
  await page.getByRole('link', { name: '기록' }).click()
  await page.getByRole('button', { name: '2026-07-01 기록' }).click()
  await expect(page.getByRole('heading', { name: '루틴을 지킨 날이에요' })).toBeVisible()
  await page.getByRole('button', { name: '닫기' }).click()
  await page.getByRole('button', { name: '데모 진행' }).click()
  await page.getByRole('button', { name: '목표 완료 보기' }).click()
  await expect(page.getByText('유럽 여행 목표를 완주했어요')).toBeVisible()
  await page.getByRole('link', { name: '새 여정 시작하기' }).click()
  await expect(page.getByText('목표 상태: 완료')).toBeVisible()
  await expect(page.getByText('RAID STAGE 3')).toBeVisible()
})
