// Generated from finmate-api/docs/vnext/06-api/openapi.yaml. Do not edit.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/auth/signup": {
    post: operations["signUp"];
  };
  "/auth/login": {
    post: operations["logIn"];
  };
  "/auth/refresh": {
    post: operations["refreshSession"];
  };
  "/auth/logout": {
    post: operations["logOut"];
  };
  "/onboarding": {
    get: operations["getOnboarding"];
    put: operations["completeOnboarding"];
  };
  "/goals/active": {
    get: operations["getActiveUserGoal"];
  };
  "/home": {
    get: operations["getHome"];
  };
  "/raids/current": {
    get: operations["getCurrentRaid"];
  };
  "/reports/monthly": {
    get: operations["getMonthlyReport"];
  };
  "/mate/groups": {
    get: operations["listMateGroups"];
  };
  "/mate/groups/{groupId}/adventurers": {
    get: operations["listRecommendedAdventurers"];
  };
  "/mate/groups/{groupId}/adventurers/{adventurerId}/routines/{routineId}": {
    get: operations["getAdventurerRoutine"];
  };
  "/routine-adaptations": {
    post: operations["createRoutineAdaptation"];
  };
  "/routine-adaptations/{adaptationId}/choice": {
    put: operations["chooseRoutineAdaptationDomain"];
  };
  "/routine-adaptations/{adaptationId}/candidates/{candidateId}/import": {
    post: operations["importRoutineAdaptationCandidate"];
  };
  "/routine-builds/active": {
    get: operations["getActiveRoutineBuild"];
  };
  "/routine-builds/active/replacement": {
    post: operations["replaceActiveRoutineBuild"];
  };
  "/quests": {
    get: operations["listQuests"];
  };
  "/quests/{questId}": {
    get: operations["getQuest"];
  };
  "/quests/{questId}/complete": {
    post: operations["completeQuest"];
  };
  "/records": {
    get: operations["listDailyRecords"];
  };
  "/records/{date}": {
    get: operations["getDailyRecord"];
    put: operations["saveDailyReflection"];
  };
  "/demo/timeline/advance": {
    /** @description Registered only under the Spring demo profile. Never exposed in production. */
    post: operations["advanceDemoTimeline"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Format: int64
     * @description Whole Korean won
     */
    KrwAmount: number;
    BasisPoints: number;
    /** Format: date-time */
    Timestamp: string;
    /** @enum {string} */
    DataState: "FRESH" | "PENDING" | "STALE" | "INSUFFICIENT";
    /** @enum {string} */
    GoalDomain: "SPENDING" | "SAVING";
    /** @enum {string} */
    AdaptationDomain: "SPENDING" | "SAVING" | "INVESTMENT_JUDGMENT";
    /** @enum {string} */
    Difficulty: "LIGHT" | "STANDARD" | "CHALLENGE";
    /** @enum {string} */
    TargetKind: "AMOUNT_KRW" | "RATIO_BPS" | "BEHAVIOR";
    SignUpRequest: {
      /** Format: email */
      email: string;
      password: string;
      displayName: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    UserSummary: {
      /** Format: uuid */
      userId: string;
      /** Format: email */
      email: string;
      displayName: string;
      /** @enum {string} */
      onboardingStatus: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
    };
    AuthSession: {
      accessToken: string;
      /** @enum {string} */
      tokenType: "Bearer";
      expiresAt: components["schemas"]["Timestamp"];
      user: components["schemas"]["UserSummary"];
    };
    CompleteOnboardingRequest: {
      displayName: string;
      mainGoal: components["schemas"]["UserGoalDraft"];
      /** @enum {boolean} */
      confirmMainGoal: true;
    };
    UserGoalDraft: {
      title: string;
      domain: components["schemas"]["GoalDomain"];
      currentAmountKrw: components["schemas"]["KrwAmount"];
      targetAmountKrw: components["schemas"]["KrwAmount"];
      targetMonth: string;
    };
    UserGoal: {
      goalId: string;
      title: string;
      domain: components["schemas"]["GoalDomain"];
      currentAmountKrw: components["schemas"]["KrwAmount"];
      targetAmountKrw: components["schemas"]["KrwAmount"];
      targetMonth: string;
      /** @enum {string} */
      state: "ACTIVE" | "COMPLETED" | "ARCHIVED";
      confirmedAt: components["schemas"]["Timestamp"];
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    OnboardingView: {
      /** @enum {string} */
      status: "DRAFT" | "COMPLETED";
      displayName: string | null;
      mainGoal: components["schemas"]["UserGoal"] | null;
    };
    FinancialStats: {
      spendingBps: components["schemas"]["BasisPoints"];
      savingBps: components["schemas"]["BasisPoints"];
      investmentJudgmentBps: components["schemas"]["BasisPoints"];
    };
    RaidView: {
      raidId: string;
      goalId: string;
      stage: number;
      bossHpBps: components["schemas"]["BasisPoints"];
      progressBps: components["schemas"]["BasisPoints"];
      financialStats: components["schemas"]["FinancialStats"];
      xp: number;
      coachCopyKey: string;
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    HomeResponse: {
      mainGoal: components["schemas"]["UserGoal"];
      raid: components["schemas"]["RaidView"];
      activeRoutineBuild: components["schemas"]["ActiveRoutineBuild"] | null;
      nextQuest: components["schemas"]["Quest"] | null;
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    MonthlyReport: {
      month: string;
      goalProgressBps: components["schemas"]["BasisPoints"];
      financialStats: components["schemas"]["FinancialStats"];
      xpEarned: number;
      completedQuestCount: number;
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    MateGroup: OneOf<[{
      groupId: string;
      name: string;
      memberCount: number;
      /** @enum {boolean} */
      syntheticDemo: false;
      /** @enum {boolean} */
      eligibleForProductionAggregation: true;
    }, {
      groupId: string;
      name: string;
      /** @enum {integer} */
      memberCount: 10;
      /** @enum {boolean} */
      syntheticDemo: true;
      /** @enum {boolean} */
      eligibleForProductionAggregation: false;
    }]>;
    MateGroupPage: {
      items: components["schemas"]["MateGroup"][];
    };
    RoutineSummary: {
      routineId: string;
      title: string;
      availableDomains: components["schemas"]["AdaptationDomain"][];
    };
    RecommendedAdventurerCard: {
      adventurerId: string;
      groupId: string;
      alias: string;
      similarityReasons: string[];
      routines: components["schemas"]["RoutineSummary"][];
      approvedAt: components["schemas"]["Timestamp"];
    };
    RecommendedAdventurerPage: {
      groupId: string;
      items: components["schemas"]["RecommendedAdventurerCard"][];
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    AdventurerRoutine: {
      routineId: string;
      adventurerId: string;
      groupId: string;
      title: string;
      description: string;
      availableDomains: components["schemas"]["AdaptationDomain"][];
      maintainedDays: number;
    };
    CreateRoutineAdaptationRequest: {
      groupId: string;
      adventurerId: string;
      routineId: string;
    };
    ChooseAdaptationDomainRequest: {
      domain: components["schemas"]["AdaptationDomain"];
    };
    RoutineAdaptationCandidate: OneOf<[{
      candidateId: string;
      difficulty: components["schemas"]["Difficulty"];
      /** @enum {string} */
      domain: "SPENDING" | "SAVING";
      title: string;
      /** @enum {string} */
      targetKind: "AMOUNT_KRW";
      targetAmountKrw: components["schemas"]["KrwAmount"];
      steps: string[];
    }, {
      candidateId: string;
      difficulty: components["schemas"]["Difficulty"];
      /** @enum {string} */
      domain: "SPENDING" | "SAVING";
      title: string;
      /** @enum {string} */
      targetKind: "RATIO_BPS";
      targetRatioBps: components["schemas"]["BasisPoints"];
      steps: string[];
    }, {
      candidateId: string;
      difficulty: components["schemas"]["Difficulty"];
      domain: components["schemas"]["AdaptationDomain"];
      title: string;
      /** @enum {string} */
      targetKind: "BEHAVIOR";
      behaviorTarget: string;
      steps: string[];
    }]>;
    RoutineAdaptationSet: {
      adaptationId: string;
      sourceRoutineId: string;
      /** @enum {string} */
      state: "CANDIDATES_READY";
      selectedDomain: components["schemas"]["AdaptationDomain"];
      light: components["schemas"]["RoutineAdaptationCandidate"] & {
        /** @enum {string} */
        difficulty: "LIGHT";
      };
      standard: components["schemas"]["RoutineAdaptationCandidate"] & {
        /** @enum {string} */
        difficulty: "STANDARD";
      };
      challenge: components["schemas"]["RoutineAdaptationCandidate"] & {
        /** @enum {string} */
        difficulty: "CHALLENGE";
      };
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    ActiveRoutineBuild: {
      buildId: string;
      candidateId: string;
      sourceRoutineId: string;
      domain: components["schemas"]["AdaptationDomain"];
      difficulty: components["schemas"]["Difficulty"];
      /** @enum {string} */
      status: "ACTIVE" | "COMPLETED" | "ARCHIVED";
      steps: string[];
      activatedAt: components["schemas"]["Timestamp"];
      archivedAt?: components["schemas"]["Timestamp"] | null;
      replacesBuildId: string | null;
      replacedByBuildId?: string | null;
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    ReplaceActiveRoutineBuildRequest: {
      adaptationId: string;
      candidateId: string;
      /** @enum {boolean} */
      confirmReplacement: true;
    };
    RoutineBuildReplacement: {
      archivedBuild: components["schemas"]["ActiveRoutineBuild"];
      activeBuild: components["schemas"]["ActiveRoutineBuild"];
      replacedAt: components["schemas"]["Timestamp"];
    };
    Quest: {
      questId: string;
      title: string;
      /** @enum {string} */
      status: "AVAILABLE" | "ACTIVE" | "DATA_PENDING" | "COMPLETED" | "EXPIRED" | "CANCELLED";
      /** @enum {string} */
      verificationKind: "BEHAVIOR" | "SYNTHETIC_MYDATA";
      xpReward: number;
      internalRewardCodes: string[];
      /** @enum {boolean} */
      financialStatsChanged: false;
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    QuestPage: {
      items: components["schemas"]["Quest"][];
      totalXp: number;
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    QuestCompletion: {
      quest: components["schemas"]["Quest"];
      xpAwarded: number;
      internalRewardCodes: string[];
      /** @enum {boolean} */
      financialStatsChanged: false;
    };
    RecordEvent: {
      /** @enum {string} */
      eventType: "QUEST" | "ROUTINE_BUILD" | "MYDATA_RECALCULATION";
      occurredAt: components["schemas"]["Timestamp"];
      title: string;
    };
    DailyRecord: {
      /** Format: date */
      date: string;
      events: components["schemas"]["RecordEvent"][];
      xpEarned: number;
      reflection: string | null;
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    DailyRecordPage: {
      items: components["schemas"]["DailyRecord"][];
      calculationVersion: string;
      dataState: components["schemas"]["DataState"];
      lastSyncedAt: components["schemas"]["Timestamp"] | null;
    };
    SaveReflectionRequest: {
      reflection: string;
    };
    AdvanceDemoTimelineRequest: {
      /** @enum {string} */
      fixtureId: "EUROPE_TRAVEL_JANUARY";
      expectedStage: number;
    };
    DemoTimelineView: {
      /** @enum {string} */
      fixtureId: "EUROPE_TRAVEL_JANUARY";
      stage: number;
      mainGoal: components["schemas"]["UserGoal"];
      raid: components["schemas"]["RaidView"];
      syntheticGroup: components["schemas"]["MateGroup"];
    };
    FieldError: {
      field: string;
      message: string;
    };
    Problem: {
      /** Format: uri */
      type: string;
      title: string;
      status: number;
      detail: string;
      instance: string;
      /** @enum {string} */
      code: "VALIDATION_FAILED" | "UNAUTHORIZED" | "INVALID_CREDENTIALS" | "DUPLICATE_EMAIL" | "NOT_FOUND" | "DATA_STALE" | "DATA_INSUFFICIENT" | "ACTIVE_ROUTINE_BUILD_EXISTS" | "ADAPTATION_DOMAIN_REQUIRED" | "DEMO_PROFILE_REQUIRED";
      traceId: string;
      fieldErrors?: components["schemas"]["FieldError"][];
    };
  };
  responses: {
    /** @description Authenticated email/password session */
    AuthSessionResponse: {
      headers: {
        "Set-Cookie": components["headers"]["RefreshCookie"];
      };
      content: {
        "application/json": components["schemas"]["AuthSession"];
      };
    };
    /** @description RFC 7807 problem */
    ProblemResponse: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description An active routine build exists and explicit replacement is required */
    ActiveBuildConflict: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The last synthetic calculation is too old for this command */
    DataStale: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description Synthetic source periods or classifications are insufficient */
    DataInsufficient: {
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    IdempotencyKey: string;
    /** @description Opaque 30-day refresh token. Sent only as an HttpOnly, SameSite=Lax cookie scoped to /api/v1/auth. */
    RefreshCookie: string;
    GroupId: string;
    AdventurerId: string;
    RoutineId: string;
    AdaptationId: string;
    CandidateId: string;
    QuestId: string;
    RecordDate: string;
  };
  requestBodies: never;
  headers: {
    /**
     * @description Rotated opaque refresh token; HttpOnly, SameSite=Lax, Path=/api/v1/auth, Max-Age=2592000. Secure is enabled outside local development.
     * @example finmate_refresh=opaque-token; Path=/api/v1/auth; Max-Age=2592000; HttpOnly; SameSite=Lax; Secure
     */
    RefreshCookie: string;
    /**
     * @description Revokes the browser cookie with Max-Age=0 using the same attributes and path.
     * @example finmate_refresh=; Path=/api/v1/auth; Max-Age=0; HttpOnly; SameSite=Lax; Secure
     */
    ClearedRefreshCookie: string;
  };
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  signUp: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      201: components["responses"]["AuthSessionResponse"];
      default: components["responses"]["ProblemResponse"];
    };
  };
  logIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      200: components["responses"]["AuthSessionResponse"];
      default: components["responses"]["ProblemResponse"];
    };
  };
  refreshSession: {
    parameters: {
      cookie: {
        finmate_refresh: components["parameters"]["RefreshCookie"];
      };
    };
    responses: {
      200: components["responses"]["AuthSessionResponse"];
      default: components["responses"]["ProblemResponse"];
    };
  };
  logOut: {
    parameters: {
      cookie: {
        finmate_refresh: components["parameters"]["RefreshCookie"];
      };
    };
    responses: {
      /** @description Refresh session revoked and cookie cleared */
      204: {
        headers: {
          "Set-Cookie": components["headers"]["ClearedRefreshCookie"];
        };
        content: never;
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  getOnboarding: {
    responses: {
      /** @description Current onboarding draft or completed state */
      200: {
        content: {
          "application/json": components["schemas"]["OnboardingView"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  completeOnboarding: {
    parameters: {
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteOnboardingRequest"];
      };
    };
    responses: {
      /** @description Onboarding completed with one confirmed goal */
      200: {
        content: {
          "application/json": components["schemas"]["OnboardingView"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  getActiveUserGoal: {
    responses: {
      /** @description The one active main goal */
      200: {
        content: {
          "application/json": components["schemas"]["UserGoal"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  getHome: {
    responses: {
      /** @description Home tab projection */
      200: {
        content: {
          "application/json": components["schemas"]["HomeResponse"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  getCurrentRaid: {
    responses: {
      /** @description Current raid projection from financial evidence */
      200: {
        content: {
          "application/json": components["schemas"]["RaidView"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  getMonthlyReport: {
    parameters: {
      query: {
        month: string;
      };
    };
    responses: {
      /** @description Monthly financial and activity report */
      200: {
        content: {
          "application/json": components["schemas"]["MonthlyReport"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  listMateGroups: {
    responses: {
      /** @description Eligible operational groups and explicit synthetic demo group */
      200: {
        content: {
          "application/json": components["schemas"]["MateGroupPage"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  listRecommendedAdventurers: {
    parameters: {
      path: {
        groupId: components["parameters"]["GroupId"];
      };
    };
    responses: {
      /** @description Anonymous adventurers recommended inside the selected group */
      200: {
        content: {
          "application/json": components["schemas"]["RecommendedAdventurerPage"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  getAdventurerRoutine: {
    parameters: {
      path: {
        groupId: components["parameters"]["GroupId"];
        adventurerId: components["parameters"]["AdventurerId"];
        routineId: components["parameters"]["RoutineId"];
      };
    };
    responses: {
      /** @description Routine detail within group and anonymous adventurer context */
      200: {
        content: {
          "application/json": components["schemas"]["AdventurerRoutine"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  createRoutineAdaptation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRoutineAdaptationRequest"];
      };
    };
    responses: {
      /** @description Adaptation awaiting the user's single domain choice */
      201: {
        content: {
          "application/json": {
            adaptationId: string;
            sourceRoutineId: string;
            /** @enum {string} */
            state: "AWAITING_DOMAIN";
            availableDomains: components["schemas"]["AdaptationDomain"][];
            calculationVersion: string;
            dataState: components["schemas"]["DataState"];
            lastSyncedAt: components["schemas"]["Timestamp"] | null;
          };
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  chooseRoutineAdaptationDomain: {
    parameters: {
      path: {
        adaptationId: components["parameters"]["AdaptationId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChooseAdaptationDomainRequest"];
      };
    };
    responses: {
      /** @description Three candidates for the selected domain */
      200: {
        content: {
          "application/json": components["schemas"]["RoutineAdaptationSet"];
        };
      };
      409: components["responses"]["DataStale"];
      422: components["responses"]["DataInsufficient"];
      default: components["responses"]["ProblemResponse"];
    };
  };
  importRoutineAdaptationCandidate: {
    parameters: {
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        adaptationId: components["parameters"]["AdaptationId"];
        candidateId: components["parameters"]["CandidateId"];
      };
    };
    responses: {
      /** @description New global active routine build when none exists */
      201: {
        content: {
          "application/json": components["schemas"]["ActiveRoutineBuild"];
        };
      };
      409: components["responses"]["ActiveBuildConflict"];
      default: components["responses"]["ProblemResponse"];
    };
  };
  getActiveRoutineBuild: {
    responses: {
      /** @description The one global active routine build */
      200: {
        content: {
          "application/json": components["schemas"]["ActiveRoutineBuild"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  replaceActiveRoutineBuild: {
    parameters: {
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplaceActiveRoutineBuildRequest"];
      };
    };
    responses: {
      /** @description Previous build archived and candidate build activated atomically */
      200: {
        content: {
          "application/json": components["schemas"]["RoutineBuildReplacement"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  listQuests: {
    responses: {
      /** @description Quest tab projection */
      200: {
        content: {
          "application/json": components["schemas"]["QuestPage"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  getQuest: {
    parameters: {
      path: {
        questId: components["parameters"]["QuestId"];
      };
    };
    responses: {
      /** @description Quest detail */
      200: {
        content: {
          "application/json": components["schemas"]["Quest"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  completeQuest: {
    parameters: {
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        questId: components["parameters"]["QuestId"];
      };
    };
    responses: {
      /** @description Completion grants XP/internal rewards without changing financial stats */
      200: {
        content: {
          "application/json": components["schemas"]["QuestCompletion"];
        };
      };
      /** @description Financial evidence awaits synthetic MyData recalculation */
      202: {
        content: {
          "application/json": components["schemas"]["QuestCompletion"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  listDailyRecords: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
    };
    responses: {
      /** @description Daily record page */
      200: {
        content: {
          "application/json": components["schemas"]["DailyRecordPage"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  getDailyRecord: {
    parameters: {
      path: {
        date: components["parameters"]["RecordDate"];
      };
    };
    responses: {
      /** @description One daily record */
      200: {
        content: {
          "application/json": components["schemas"]["DailyRecord"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  saveDailyReflection: {
    parameters: {
      path: {
        date: components["parameters"]["RecordDate"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveReflectionRequest"];
      };
    };
    responses: {
      /** @description Daily record with saved reflection; calculations are unchanged */
      200: {
        content: {
          "application/json": components["schemas"]["DailyRecord"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
  /** @description Registered only under the Spring demo profile. Never exposed in production. */
  advanceDemoTimeline: {
    parameters: {
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdvanceDemoTimelineRequest"];
      };
    };
    responses: {
      /** @description Advanced synthetic fixture stage and recalculated projections */
      200: {
        content: {
          "application/json": components["schemas"]["DemoTimelineView"];
        };
      };
      default: components["responses"]["ProblemResponse"];
    };
  };
}
